---
title: "Weekly Lesson Plan"
editor: visual
---

| Week | Date       | Topic                                                                                            | Remarks |
|------------------|------------------|--------------------|------------------|
| 1    | 14/8/2023  | [Lesson 1: Introduction to GIS for Urban Planning](outline/lesson01_outline.html)                |         |
| 2    | 21/8/2023  | [Lesson 2: The Evil is in The Data](outline/lesson02_outline.html)                               |         |
| 3    | 28/8/2023  | [Lesson 3: Mapping and Visualising Urban World with GIS](outline/lesson03_outline.html)          |         |
| 4    | 4/9/2023   | [Lesson 4: Vector-based GeoProcessing and GIS Analysis](outline/lesson04_outline.html)           |         |
| 5    | 11/9/2023  | [Lesson 5: Urban Applications of Vector-based GIS Analysis](outline/lesson05_outline.html)       |         |
| 6    | 18/9/2023  | [Lesson 6: The Science of Mapthematics](outline/lesson06_outline.html)                           |         |
| 7    | 25/9/2023  | [Lesson 7: GIS-based Multi-Criteria Decision Analysis](outline/lesson07_outline.html)            |         |
| 8    | 2/10/2023  | Mid-term break                                                                                   |         |
| 9    | 9/10/2023  | [Lesson 8: Introduction to Digital Image Processing and Analysis](outline/lesson08_outline.html) |         |
| 10   | 16/10/2023 | [Lesson 9: Applied Image Analysis for the Urban Environment](outline/lesson09_outline.html))     |         |
| 11   | 23/10/2023 | [Lesson 10: Urban Network Analysis with GIS](outline/lesson10_outline.html)                      |         |
| 12   | 30/10/2023 | [Lesson 11: Geographic Accessibility Analysis with GIS](outline/lesson11_outline.html)               |         |
| 13   | 6/11/2023  | [Lesson 12: Sharing Geographical Information](outline/lesson12_outline.html)                     |         |
| 14   | 13/11/2023 | Townhall Presentation                                                                            |         |
