---
title: "Take-home Exercise 1: Urban Applications of Vector-based GIS Analysis"
date: "Septermber 5, 2023"
date-modified: "last-modified"
format: html
---

## Overview

This handout provides the context, task, expectations and grading criteria of Take-home Exercise 1. Students must review and understand them before getting started with the take-home exercise.

## Setting the Scene

Human mobility, the movement of human beings in space and time, reflects the spatial-temporal characteristics of human behavior. With the advancement Information and Communication Technologies (ICT) especially smart phone, a large volume of data related to human mobility have been collected. By using appropriate GIS analysis methods, these data are potentially useful in supporting smart city planning and management.

In Singapore, one of the important source of data related to human mobility is from [Land Transport Authority (LTA) DataMall](https://datamall.lta.gov.sg/content/datamall/en.html). Two data sets related to human mobility are provided by the portal, they are: Passenger Volume by Origin Destination Train Stations and Passenger Volume by Origin Destination Bus Stops. One of the limitation of these data sets is that their location are biased to either bus stops or MRT/LRT stations. In 2020, another very interesting human mobility data set called [Grab Posisi](https://engineering.grab.com/grab-posisi) was released by GRAB, one of the largest shared taxi operator in South-east Asia. There are two data sets been released and one of them is for Singapore.

## Task

In this take-home exercise, we are interested to explore the potential use of Grab Posisi data set to gain better understanding of the spatial-temporal patterns of human mobility in Singapore and how these patterns are related urban activities such as place of work, study and recreation, just to name a few of them.

The specific tasks of this hands-on exercise are as follow:

-   Derive an [analytical hexagon](https://gis4urbplan.netlify.app/hands-on_ex10#analytical-hexagon) GIS data by using appropriate GIS analysis function of QGIS.
-   Process, wrangling and organise Grab Posisi data set spatio-temporally by using the analytical hexagon layer.
-   Prepare a series of thematic maps by using appropriate mapping techniques showing the spatio-temporal patterns of human mobility at one-hour interval.
-   For each thematic map prepared, write a short report of not more than 100 words describing the spatio-temporal patterns revealed by the map.
-   Assemble at least five urban functions such as place to stay, education, work, shopping and recreation etc.
-   With reference to the above urban functions GIS data, analyse and visualise the relationship between urban mobility and the selected urban functions.
-   For each thematic map prepared, write a short report of not more than 100 words describing the relationship revealed by the map.
-   With reference to the analysis results above, discuss how these findings can be used to support smart city planning and management. (Not more than 250 words)

## Data

For the purpose of this study, a subset of 28000 trips of the complete Grab Posisi data are provided. It is available at Take-home Exercise 1 of eLearn. Please refer to the web article entitle [Grab-Posisi - Southeast Asia's First Comprehensive GPS Trajectory Dataset](https://engineering.grab.com/grab-posisi) for more details including the data dictionary of the data set.

## Take-home Exercise Deliverable

### GIS data repository

The GIS repository includes but not limited to geospatial data compiled and derived, QGIS project file and data dictionary. It must be in a single zipped file (i.e. .zip). The geospatial data must be stored in a GeoPackage database format. The data dictionary can be in either MS Word document or edited into the GIS data.The project deliverable must be uploaded onto eLearn.

### Take-home Exercise Report

You are required to edit your take-home exercise report in MS Word format. The take-home exercise report, beside others, should include all the thematic maps prepared and their respective discussion.

More importantly, the report must provide a **reproducible** step-by-step guide on the following process:

-   data compilation, extraction and integration,
-   data cleaning, preparation and wrangling,
-   GIS analysis (including tabular and graphical analysis), and
-   GIS maps design.

> Note: **Reproducible** means that readers are able to perform the same analysis and obtain similar results by using the same data sets and by following the step-by-step guide.

The title of the report should be in the form of *SMT201_AY2023-24T1_Take-home_Exercise1*.

> Note: This is an individual exercise. You are required to work on the take home exercise and prepare submission individually.

## Grading

-   Quality of the GIS data model built (including metadata) (20 marks),
-   Appropriateness of the GIS methods used (20 marks),
-   Quality of GIS maps prepared (20 marks),
-   Reproducibility of the GIS processes (20 marks)
-   Ability to provide correct interpretation of the analysis results and to recommend appropriate alternatives (20 marks).

## Submission Date

The take-home exercise deliverable must be uploaded on eLearn by the submission deadline stated below.

Due Date: **17th September 2023, 11:59pm (midnight)**.
